### ISSUE TITLE
[BUG] No module named 'setuptools_scm'

### ISSUE THREAD

**Issue by yijingchen** [microsoft/nlp#301]
### Description

This module 'setuptools_scm' is not part of the environment installation.

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-3bf2c9e5562d> in <module>
      6 
      7 #import utils
----> 8 from utils_nlp.common.timer import Timer
      9 from utils_nlp.azureml import azureml_utils
     10 

/data/home/yijichen/notebooks/nlp_repo/nlp-2/utils_nlp/__init__.py in <module>
----> 1 from setuptools_scm import get_version
      2 
      3 # Determine semantic versioning automatically
      4 # from git commits
      5 __version__ = get_version()

ModuleNotFoundError: No module named 'setuptools_scm'
```

### How do we replicate the bug?

Use 'staging' branch.
Run any notebook where we import Timer. For example, you can see this error when running 'question_answering_system_bidaf_quickstart' notebook. 

### Expected behavior (i.e. solution)

No error.

**Comment by heatherbshapiro** [comment]
I'm still seeing this issue on a fresh conda environment. Is there a workaround?

**Comment by awaemmanuel** [comment]
@heatherbshapiro Latest `staging` shouldn't even have `setuptools_scm` at all.
