### ISSUE TITLE
[BUG] RemoveError: 'requests' is a dependency of conda and cannot be removed from conda's operating environment.

### ISSUE THREAD

**Issue by jaymathe** [microsoft/nlp#305]
### Description
Unable to create the conda environment, here is the error I got 
RemoveError: 'requests' is a dependency of conda and cannot be removed from
conda's operating environment.

### How do we replicate the bug?
I am following the steps on this page https://github.com/microsoft/nlp/blob/master/SETUP.md
I already have a conda environment called nlp_cpu, hence I was trying to create a new environment called nlp_repo_cpu. 
When I run this line: conda env create -f nlp_cpu.yaml 
I run into this error: 
RemoveError: 'requests' is a dependency of conda and cannot be removed from
conda's operating environment.

How do I go about fixing this issue?

**Comment by jaymathe** [comment]
Thanks! I was able to fix this issue with a new conda environment setup.

**Comment by Asingh421** [comment]
I am getting the same issue...i tried updating conda that too throwing the same error

**Comment by guss77** [comment]
Currently `--force` appears to be deprecated. I use `conda update --force-reinstall conda` to get the update working.
