### ISSUE TITLE
[ASK] Remove 'repo_metrics' folder

### ISSUE THREAD

**Issue by yijingchen** [microsoft/nlp#319]
### Description

During the team discussion, we believe that the files in this ['repo_metrics' folder](https://github.com/microsoft/nlp/tree/master/tools/repo_metrics) should be removed from the NLP repo and create a centralized way to maintain it.

**Comment by simonzhaoms** [comment]
It looks good! @yijingchen 

One suggestion:
* It would be easier to maintain if the 3 `xxx_repo_metrics_pipeline.yml` are combined into one `repo_metrics_pipeline.yml` since most of the code are the same.  That would need to define 3 set of variables, e.g. `xxx_github_token`, `xxx_cosmosdb_connectionstring` and `xxx_database` for each of the repos separately.

I have not much experience in Azure DevOps, not sure if it is common practice.

**Comment by yijingchen** [comment]
@simonzhaoms Thanks a lot for the suggestion. I already made the token, cosmosdb and data base as variables in the current pipeline. To combine the script, I'll need to make the repo link as variable as well. The link is passed in a bit differently than the tokens so I'll need to modify some python scripts. Will look into it tomorrow.
Btw, if we do this merge, then we are forcing each repo tracking exactly the same (meaning same schedule, same tracking stats, etc.) Would this work for all BPs?

**Comment by simonzhaoms** [comment]
@yijingchen I think they are tracking exactly the same since they use the same code in [`repo_metrics`](https://dev.azure.com/AZGlobal/AGCE%20Development/_git/BP-Metrics-Tracking?path=%2Frepo_metrics&version=GBmaster). The only differences I know is the variables and the dashboards which are just different view of the data.

**Comment by yueguoguo** [comment]
@yijingchen late to the party 😄. Just a quick one, in the new pipeline you have set up, have we preserved the historical stats data as well?

**Comment by yijingchen** [comment]
> @yijingchen I think they are tracking exactly the same since they use the same code in repo_metrics. The only differences I know is the variables and the dashboards which are just different view of the data.

Sounds good. I'll merge the scripts then. @simonzhaoms Do you know where is the dashboard for the BPs?

**Comment by yijingchen** [comment]
> @yijingchen late to the party 😄. Just a quick one, in the new pipeline you have set up, have we preserved the historical stats data as well?

@yuegougou I haven't done the data migration yet because I don't know if the subscription and DevOps is the right place to host. Once we agree on a common place to host, I can import the data from the old cosmosdb to this new one. Do you know if I'm putting the pipeline and db in the right place? (The other option for pipelines is Best Practice DevOps, and other option for cosmos db is E2E subscription, or reuse the existing db.)

**Comment by simonzhaoms** [comment]
@yijingchen 
* For the right place to host, how about we just keep it until changes are needed?
* I only know [cvbp's dashboard](https://msit.powerbi.com/groups/1feb1708-59d1-4112-a293-2147a40eba2e/dashboards/7a7a126c-153d-4c6d-b11b-30f552334f77?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47) is under [this workspace](https://msit.powerbi.com/groups/1feb1708-59d1-4112-a293-2147a40eba2e/list/dashboards?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47) (permission needed).  I have no permission to other dashboards.

**Comment by miguelgfierro** [comment]
@yijingchen in a previous conversation with @gramhagen we talked about creating a github repo and a pipy package so we can add it externally to the bp repos. Is that still the plan or has this changed?

**Comment by gramhagen** [comment]
i think it's still an option, this was just the path of least resistance. if there was a pypi package then it would be easy to replace in devops

**Comment by yijingchen** [comment]
> @yijingchen in a previous conversation with @gramhagen we talked about creating a github repo and a pipy package so we can add it externally to the bp repos. Is that still the plan or has this changed?

@miguelgfierro It's still an option. This is a midway plan between publishing a new pypi package and duplicate tracking code in all repos. 

I don't know how many levels of approval we need in order to publish a new pipy package. We can choose A) do no change till we have the pipy package. B) move the tracking code to another place for now and work on the pipy package when the team has bandwidth
What's your perspective?

**Comment by yueguoguo** [comment]
+1 on the concern about the timeliness for getting a PyPI package publicized. It might be great to prioritize with local codes, and move to a PyPI package once it is ready.

**Comment by miguelgfierro** [comment]
that's reasonable

**Comment by yijingchen** [comment]
> It looks good! @yijingchen
> One suggestion:
> 
> It would be easier to maintain if the 3 xxx_repo_metrics_pipeline.yml are combined into one repo_metrics_pipeline.yml since most of the code are the same.  That would need to define 3 set of variables, e.g. xxx_github_token, xxx_cosmosdb_connectionstring and xxx_database for each of the repos separately.
> 
> I have not much experience in Azure DevOps, not sure if it is common practice.

@simonzhaoms I have updated the [repo](https://dev.azure.com/AZGlobal/AGCE%20Development/_git/BP-Metrics-Tracking?path=%2Fpipelines%2Fmetrics_pipeline.yml&version=GBmaster) and the [pipelines](https://dev.azure.com/AZGlobal/AGCE%20Development/_build?definitionId=13) based on your suggestion. Now we have 1 yml file and each pipeline just need to provide an extra parameter for github repo address. Please feel free to let me know if you have other suggestion on this. Thanks!

**Comment by simonzhaoms** [comment]
@yijingchen It looks good!

BTW, no worry about duplicated records in cosmosdb because duplicated records can be filtered out when loaded for display on dashboard.  And they are already filtered out in Reco and CVBP's dashboard I think.  In other words, if there are two pipelines simultaneously storing the same number of stars for Reco on today for example (that is two rows with the same timestamp in the cosmosdb table), only one of them will be used to be displayed on Reco's dashboard.

**Comment by yijingchen** [comment]
@simonzhaoms Thank you so much Simon. This great to know!
