### ISSUE TITLE
installation of utils_nlp should be moved inside the conda yml file generation script

### ISSUE THREAD

**Issue by georgeAccnt-GH** [microsoft/nlp#358]
### Description
installation of utils_nlp should be moved inside the conda yml file generation script 

### How do we replicate the bug?
Install instructions describe the utils package installation after the user is guided to activate the nlp conda env and start a notebook

### Expected behavior (i.e. solution)
git+git@github.com:microsoft/nlp.git@master#egg=utils_nlp should be added in the pip section of the generated conda yml file

**Comment by awaemmanuel** [comment]
@georgeAccnt-GH I tried this initially and it caused a lot of weird behaviors where conda installed it. It was installed but I couldn't import it.
