### ISSUE TITLE
[ASK] How do i get the azureml setup done for the notebook? 

### ISSUE THREAD

**Issue by jaymathe** [microsoft/nlp#379]
### Description
For some of the notebooks when I try to import the azure ml modules, I run into this error: is there some additional prep that needs to be done to import the azure ml modules? 

Failure while loading azureml_run_type_providers. Failed to load entrypoint hyperdrive = azureml.train.hyperdrive:HyperDriveRun._from_run_dto with exception (azureml-core 1.0.57.1 (/data/anaconda/envs/nlp_gpu/lib/python3.6/site-packages), Requirement.parse('azureml-core==1.0.48.*')).
Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.PipelineRun = azureml.pipeline.core:PipelineRun._from_dto with exception (azureml-core 1.0.57.1 (/data/anaconda/envs/nlp_gpu/lib/python3.6/site-packages), Requirement.parse('azureml-core==1.0.48.*')).
Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.ReusedStepRun = azureml.pipeline.core:StepRun._from_reused_dto with exception (azureml-core 1.0.57.1 (/data/anaconda/envs/nlp_gpu/lib/python3.6/site-packages), Requirement.parse('azureml-core==1.0.48.*')).
Failure while loading azureml_run_type_providers. Failed to load entrypoint azureml.StepRun = azureml.pipeline.core:StepRun._from_dto with exception (azureml-core 1.0.57.1 (/data/anaconda/envs/nlp_gpu/lib/python3.6/site-packages), Requirement.parse('azureml-core==1.0.48.*')).

**Comment by jaymathe** [comment]
Does this setup need to be done to prevent these errors:
You will need to do the following to be successful with the rest of the notebook:

    Have an existing Azure subscription. You can get started for free here

    Understand the architecture and terms introduced by Azure Machine Learning service (AzureML)

    Make sure the AzureML Python SDK is installed with notebooks and contrib add ons.

    conda create -n azureml -y Python=3.6
    source activate azureml
    pip install --upgrade azureml-sdk[notebooks,contrib] 
    conda install ipywidgets
    jupyter nbextension install --py --user azureml.widgets
    jupyter nbextension enable azureml.widgets --user --py

    Import the required packages

    Set Environment Variables

    Connect to an Azure Machine Learning service workspace

**Comment by jaymathe** [comment]
I see it when I try and run the Jupyter notebook.

**Comment by heatherbshapiro** [comment]
Does it work if you pip install azureml-sdk[notebooks]?

**Comment by heatherbshapiro** [comment]
This should be fixed now
