### ISSUE TITLE
[BUG] Not authorized to access variable group.

### ISSUE THREAD

**Issue by bethz** [microsoft/nlp#394]
### Description

![image](https://user-images.githubusercontent.com/6098674/64176278-169fd580-ce2b-11e9-9c12-66c0479f2329.png)

### How do we replicate the bug?
I am not authorized to access the variable group which has the keyvault so the tests do not run.

### Expected behavior (i.e. solution)
Successful variable group access.

**Comment by miguelgfierro** [comment]
I think this was solved, feel free to reopen if not

**Comment by bethz** [comment]
not solved but I've been assigned to a new project
