### ISSUE TITLE
[BUG] AzureML related environment creation failure

### ISSUE THREAD

**Issue by hlums** [microsoft/nlp#410]
### Description

I'm trying to create a conda env on a new DSVM and got the following error
Pip subprocess error:
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/f4/d5/0549feb09daceb68db2e1a3c9582cc507692fc8f3bf4eca662d74c90992d/azureml_dataprep-1.1.8-py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/f4/d5/0549feb09daceb68db2e1a3c9582cc507692fc8f3bf4eca662d74c90992d/azureml_dataprep-1.1.8-py3-none-any.whl
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/b6/50/c6412dbcdb780d7e2253cc1c9d0dc6ea6c8cc52963e4d9aece5f1fbc654f/azureml_contrib_explain_model-1.0.57-py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/b6/50/c6412dbcdb780d7e2253cc1c9d0dc6ea6c8cc52963e4d9aece5f1fbc654f/azureml_contrib_explain_model-1.0.57-py3-none-any.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/b6/50/c6412dbcdb780d7e2253cc1c9d0dc6ea6c8cc52963e4d9aece5f1fbc654f/azureml_contrib_explain_model-1.0.57-py3-none-any.whl
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/4f/a1/3224449b9fd886f2be43173d47e8c9d42e2291bd4e6f0a9706ca6d0a4807/dotnetcore2-2.1.8-py3-none-manylinux1_x86_64.whl
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/f9/57/b39a433bf1f34d62fb4dffe581fad99562e38ea55cc64cdb714a440bcb67/nimbusml-1.4.1-cp36-none-manylinux1_x86_64.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/f9/57/b39a433bf1f34d62fb4dffe581fad99562e38ea55cc64cdb714a440bcb67/nimbusml-1.4.1-cp36-none-manylinux1_x86_64.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/f9/57/b39a433bf1f34d62fb4dffe581fad99562e38ea55cc64cdb714a440bcb67/nimbusml-1.4.1-cp36-none-manylinux1_x86_64.whl
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/f9/57/b39a433bf1f34d62fb4dffe581fad99562e38ea55cc64cdb714a440bcb67/nimbusml-1.4.1-cp36-none-manylinux1_x86_64.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",)': /packages/f9/57/b39a433bf1f34d62fb4dffe581fad99562e38ea55cc64cdb714a440bcb67/nimbusml-1.4.1-cp36-none-manylinux1_x86_64.whl
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/f9/57/b39a433bf1f34d62fb4dffe581fad99562e38ea55cc64cdb714a440bcb67/nimbusml-1.4.1-cp36-none-manylinux1_x86_64.whl (Caused by ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)",))

CondaEnvException: Pip failed

### How do we replicate the bug?

python generate_conda_file.py --gpu
conda env create -f nlp_gpu.yaml

### Expected behavior (i.e. solution)

The environment nlp_gpu should be created successfully with no error.

**Comment by miguelgfierro** [comment]
this looks like a http connection problem, and hopefully is fixed automatically, I updated a gpu environment today and it was working. Can you try again?

**Comment by hlums** [comment]
Yes. It's actually working now.
